---
# This playbook deploys the whole nodes stack.

- name: apply common configuration to all nodes
  hosts: localhost
  
  tasks:
    - name: Add terraform output to inventory
      add_host:
        host: 123.168.1.1
        group: rizon
